### ISSUE TITLE
As an project contributor I want to see my name somewhere in the list

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/election-nepal#5]
Let's create space for Team and Contributor at About Us section to recognize everyone who is engaged in the project. What say??

**Comment by studenton** [comment]
**Tasks:**
- [ ] Create section for Team
    - [ ] Name
    - [ ] Pic
    - [ ] Social Media Links
- [ ] Create Section for Contributors
